use_frameworks!

target 'RACSerialCommand_Example', :exclusive => true do
  pod 'RACSerialCommand', :path => '../'
end

target 'RACSerialCommand_Tests', :exclusive => true do
  pod 'RACSerialCommand', :path => '../'

  pod 'Kiwi'
end
